local function read(path)
    local file = assert(io.open(path, "rb"))
    local source = file:read("*a")
    file:close()
    return source
end

local function module(name, path)
    return "local " .. name .. " = (function()\n" .. read(path) .. "\nend)()\n"
end

for _, route in ipairs({ "lobby", "dungeon" }) do
    local supported = route == "dungeon" and "game.PlaceId == 85776757589518"
        or "game.PlaceId == 77649408247578 or game.PlaceId == 115445507767090"
    local parts = {
        "-- Generated by lua build.lua. Edit src/ files, then rebuild.\n",
        "if not game:IsLoaded() then game.Loaded:Wait() end\n",
        "if not (" .. supported .. ") then\n"
            .. "    assert(loadstring(game:HttpGet(getgenv().DQObsidianLoaderURL or \"https://raw.githubusercontent.com/glitchreal/Dungeon-quest/main/main.luau\")))()\n"
            .. "    return\nend\n",
        module("Logic", "src/HubLogic.luau"),
        module("Adapter", "src/GameAdapter.luau"),
    }
    if route == "dungeon" then
        table.insert(parts, module("ThreatGeometry", "src/ThreatGeometry.luau"))
        table.insert(parts, module("AbilityController", "src/AbilityController.luau"))
        table.insert(parts, module("FarmPlanner", "src/FarmPlanner.luau"))
        table.insert(parts, "local function createController()\n" .. read("src/CombatController.luau") .. "\nend\n")
    end
    table.insert(parts, read(route == "lobby" and "src/Lobby.luau" or "src/Dungeon.luau"))
    table.insert(parts, "\n" .. read("src/ObsidianHub.luau"))
    local file = assert(io.open("dist/" .. route .. ".luau", "wb"))
    file:write(table.concat(parts))
    file:close()
    print("Built dist/" .. route .. ".luau")
end
