local Memory = dofile('src/NavigationMemory.luau')
local m = Memory.new()
local now = 100
m:observe('route|Northern Lands','edge:1>2',-1,now)
m:observe('route|Northern Lands','edge:1>2',-1,now+1)
m:observe('route|Northern Lands','edge:1>2',-1,now+2)
m:observe('route|Northern Lands','edge:1>3',1,now+3)
assert(m:choose('route|Northern Lands', {'edge:1>3','edge:1>2'}, now+4) == 'edge:1>3')
local saved=m:export();local restored=Memory.new();restored:load(saved)
assert(restored:choose('route|Northern Lands', {'edge:1>3','edge:1>2'}, now+5) == 'edge:1>3')
restored:observe('spacing|Northern Lands|boss','far',-1,now+6)
restored:observe('spacing|Northern Lands|boss','base',1,now+7)
assert(restored:summary().contexts == 2)
print('PASS bounded decaying navigation memory, persistence, and confidence reversal')
